### ISSUE TITLE
Needing Help to Set Up a test account to access citcall API

### ISSUE THREAD

**Issue by niexiongfang** [citcall/guideline_demo#2]
Hi 

As read from your API document, I need to setup an account first to access the misscall/sms API.

I was writing to request a test account from you to do some evaluation to find opportunities with CITCALL.

BTW:

I tried account registration for demo@citcall.com , but no success: never got misscall from citcall, with China mobile phone number or Indonesia mobile phone number。

And I noticed that when I inputedIndonesia mobile phone number 08138******* on page http://www.citcall.com/demo/verification.php, it prompted that “We will misscall you at +628138*******”, the leading zero of my number was removed, is that an issue?

 

Thanks in advance!

Yours,

niexiongfang

**Comment by citcall-dev** [comment]
hi niexiongfang,

the leading right will automatically become +62, since we only operate in Indonesia currently. but it will be better if you already set the country code.
and we haven't open for international number other than Indonesia number.

Indonesian number outside SEA is not guarantee by our operator currently. if you want to be created an trial account we can assist you and please give your details to mira@citcall.com

cheers,
Citcall developer
